### PR TITLE
add PirateWeather data source (based on DarkSky API)

### PR DESCRIPTION
**Pull request by mayel**

### CODE REVIEW

**Comment by kpanic** [comment]
hi @mayel 👋🏾 
could you please fix warnings when compiling and run `mix format`? But please include only your formatted files since it will format also `lib/forecastr/renderer/ascii.ex` which I don't want to format for rendering reasons.

Alternatively, if you are ok with that, I could take over the PR and land it to master based on your branch.

Thanks a lot for your contribution! Appreciated 🥇

**Comment by mayel** [comment]
Oh apologies, I usually have things set up to auto-format before committing, having a look now.

**Comment by mayel** [comment]
@kpanic I've pushed that plus a switch from Poison to Jason since that's the more modern go-to

**Comment by kpanic** [comment]
@mayel apologies to you. Thanks for fixing *my* introduced compiler errors and for maintenance 😉 
I'll make a release in the next days if that's ok!

**Comment by mayel** [comment]
@kpanic I've pushed some improvements to my fork, can't seem to PR them now

**Comment by kpanic** [comment]
@mayel mmm, weird. Maybe you can create another branch from your fork?

**Pull request merged**
